# Activate and configure extensions
# https://middlemanapp.com/advanced/configuration/#configuring-extensions

activate :autoprefixer do |prefix|
  prefix.browsers = "last 2 versions"
end

# URLs generated by link_to should be relative
set :relative_links, true

# Layouts
# https://middlemanapp.com/basics/layouts/

# Per-page layout changes
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

configure :build do
  activate :minify_css
  activate :gzip
end

configure :development do
  set :host, "http://lvh.me:4567"
  activate :livereload
end

# Directories like /subscribe/index.html should render as /subscribe on the site
activate :directory_indexes

# Asset caching (https://middlemanapp.com/advanced/improving-cacheability/)
activate :asset_hash

app.data.districts.each do |district|
  proxy "district#{district.number}/index.html", "/district.html", locals: { district: district }, ignore: true
  proxy "district#{district.number}/call/index.html", "/call.html", locals: { district: district }, ignore: true
end

# With alternative layout
# page '/path/to/file.html', layout: 'other_layout'

# Proxy pages
# https://middlemanapp.com/advanced/dynamic-pages/

# proxy(
#   '/this-page-has-no-template.html',
#   '/template-file.html',
#   locals: {
#     which_fake_page: 'Rendering a fake page with a local variable'
#   },
# )

# Helpers
# Methods defined in the helpers block are available in templates
# https://middlemanapp.com/basics/helper-methods/

# helpers do
#   def some_helper
#     'Helping'
#   end
# end

# Build-specific configuration
# https://middlemanapp.com/advanced/configuration/#environment-specific-settings

# configure :build do
#   activate :minify_css
#   activate :minify_javascript
# end
